"""Add Workspace and RBAC models

Revision ID: db2c99bc0d5b
Revises: 001_baseline
Create Date: 2026-07-14 23:55:07.778745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db2c99bc0d5b'
down_revision: Union[str, None] = '001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_id'), ['id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('google_access_token', sa.String(), nullable=True),
    sa.Column('google_refresh_token', sa.String(), nullable=True),
    sa.Column('gmail_connected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='campaignstatus'), nullable=True),
    sa.Column('throttle_per_minute', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('contact_group_ids', sa.JSON(), nullable=True),
    sa.Column('segment_criteria', sa.JSON(), nullable=True),
    sa.Column('open_tracking_enabled', sa.Boolean(), nullable=True),
    sa.Column('click_tracking_enabled', sa.Boolean(), nullable=True),
    sa.Column('opened_count', sa.Integer(), nullable=True),
    sa.Column('clicked_count', sa.Integer(), nullable=True),
    sa.Column('bounced_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('open_rate', sa.Float(), nullable=True),
    sa.Column('click_rate', sa.Float(), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('unsubscribe_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_sent_count'), ['sent_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_user_id'), ['user_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_prospect', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)

    op.create_table('crm_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('relationship_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_contact_user_email')
    )
    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_contacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_last_interaction_at'), ['last_interaction_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_user_id'), ['user_id'], unique=False)

    op.create_table('email_classification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sender_domain', sa.String(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_classification_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_classification_rules_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_classification_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_classification_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_classification_rules_sender_domain'), ['sender_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_classification_rules_sender_email'), ['sender_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_classification_rules_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_email_rule_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index('ix_email_rule_user_domain', ['user_id', 'sender_domain'], unique=False)

    op.create_table('email_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('label_ids', sa.Text(), nullable=True),
    sa.Column('internal_date', sa.DateTime(), nullable=True),
    sa.Column('body_fetched', sa.Boolean(), nullable=True),
    sa.Column('body_cache_key', sa.String(), nullable=True),
    sa.Column('ai_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gmail_message_id', name='uq_email_meta_user_gmail')
    )
    with op.batch_alter_table('email_metadata', schema=None) as batch_op:
        batch_op.create_index('ix_email_meta_user_date', ['user_id', 'internal_date'], unique=False)
        batch_op.create_index('ix_email_meta_user_sender', ['user_id', 'sender_email'], unique=False)
        batch_op.create_index('ix_email_meta_user_status', ['user_id', 'ai_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_metadata_ai_status'), ['ai_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_metadata_body_fetched'), ['body_fetched'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_metadata_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_metadata_gmail_message_id'), ['gmail_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_metadata_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_metadata_internal_date'), ['internal_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_metadata_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_metadata_sender_email'), ['sender_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_metadata_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_metadata_user_id'), ['user_id'], unique=False)

    op.create_table('forecast_accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forecast_month', sa.String(), nullable=True),
    sa.Column('forecast_date', sa.DateTime(), nullable=True),
    sa.Column('forecasted_revenue', sa.Float(), nullable=True),
    sa.Column('actual_revenue', sa.Float(), nullable=True),
    sa.Column('forecast_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('by_rep', sa.JSON(), nullable=True),
    sa.Column('by_product', sa.JSON(), nullable=True),
    sa.Column('by_region', sa.JSON(), nullable=True),
    sa.Column('variance_reasons', sa.JSON(), nullable=True),
    sa.Column('improvements_needed', sa.Text(), nullable=True),
    sa.Column('win_rate_pct', sa.Float(), nullable=True),
    sa.Column('deals_forecast', sa.Integer(), nullable=True),
    sa.Column('deals_won', sa.Integer(), nullable=True),
    sa.Column('deals_lost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_accuracy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_accuracy_id'), ['id'], unique=False)

    op.create_table('gmail_sync_cursors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('after_timestamp', sa.Integer(), nullable=True),
    sa.Column('next_page_token', sa.String(), nullable=True),
    sa.Column('last_history_id', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gmail_sync_cursors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmail_sync_cursors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gmail_sync_cursors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gmail_sync_cursors_user_id'), ['user_id'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('sales_cycle_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('avg_sales_cycle_days', sa.Float(), nullable=True),
    sa.Column('median_sales_cycle_days', sa.Float(), nullable=True),
    sa.Column('fastest_close_days', sa.Integer(), nullable=True),
    sa.Column('slowest_close_days', sa.Integer(), nullable=True),
    sa.Column('avg_stage_durations', sa.JSON(), nullable=True),
    sa.Column('stage_conversion_rates', sa.JSON(), nullable=True),
    sa.Column('stage_dropout_rates', sa.JSON(), nullable=True),
    sa.Column('deals_started', sa.Integer(), nullable=True),
    sa.Column('deals_closed', sa.Integer(), nullable=True),
    sa.Column('deals_lost', sa.Integer(), nullable=True),
    sa.Column('avg_deals_in_pipeline', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_cycle_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_cycle_metrics_id'), ['id'], unique=False)

    op.create_table('task_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('queue', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_records_queue'), ['queue'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_records_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_records_user_id'), ['user_id'], unique=False)

    op.create_table('territory_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('territory_name', sa.String(), nullable=True),
    sa.Column('territory_type', sa.String(), nullable=True),
    sa.Column('revenue_target', sa.Float(), nullable=True),
    sa.Column('revenue_actual', sa.Float(), nullable=True),
    sa.Column('revenue_variance_pct', sa.Float(), nullable=True),
    sa.Column('total_contacts', sa.Integer(), nullable=True),
    sa.Column('active_contacts', sa.Integer(), nullable=True),
    sa.Column('engaged_pct', sa.Float(), nullable=True),
    sa.Column('pipeline_value', sa.Float(), nullable=True),
    sa.Column('avg_deal_size', sa.Float(), nullable=True),
    sa.Column('deal_count', sa.Integer(), nullable=True),
    sa.Column('win_rate_pct', sa.Float(), nullable=True),
    sa.Column('avg_sales_cycle_days', sa.Float(), nullable=True),
    sa.Column('quota_attainment_pct', sa.Float(), nullable=True),
    sa.Column('growth_rate_pct', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('territory_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_territory_metrics_id'), ['id'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_id'), ['id'], unique=False)

    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('insight_type', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_insights_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_insight_type'), ['insight_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_user_id'), ['user_id'], unique=False)

    op.create_table('campaign_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_recipients_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipients_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipients_status'), ['status'], unique=False)

    op.create_table('campaign_sends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('personalized_subject', sa.String(length=255), nullable=True),
    sa.Column('personalized_body', sa.Text(), nullable=True),
    sa.Column('tracking_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'OPENED', 'CLICKED', 'BOUNCED', 'FAILED', 'RETRYING', name='emailstatus'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('opened_count', sa.Integer(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_count', sa.Integer(), nullable=True),
    sa.Column('bounced_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_sends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_sends_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_sends_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_sends_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_sends_recipient_email'), ['recipient_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_sends_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_sends_tracking_id'), ['tracking_id'], unique=True)

    op.create_table('contact_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_contact_id', sa.Integer(), nullable=False),
    sa.Column('to_contact_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('inferred_role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['to_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_relationships_id'), ['id'], unique=False)

    op.create_table('crm_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_activities_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_user_id'), ['user_id'], unique=False)

    op.create_table('crm_customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('buyer_persona', sa.String(), nullable=True),
    sa.Column('buying_style', sa.String(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('communication_style', sa.String(), nullable=True),
    sa.Column('engagement_level', sa.String(), nullable=True),
    sa.Column('company_industry', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    with op.batch_alter_table('crm_customer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_customer_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_customer_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_customer_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('crm_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('expected_close_at', sa.DateTime(), nullable=True),
    sa.Column('actual_close_at', sa.DateTime(), nullable=True),
    sa.Column('stage_moved_at', sa.DateTime(), nullable=True),
    sa.Column('close_reason', sa.String(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_deals_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_expected_close_at'), ['expected_close_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_user_id'), ['user_id'], unique=False)

    op.create_table('crm_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_interactions_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_interactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_interactions_gmail_message_id'), ['gmail_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_interactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_interactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_interactions_user_id'), ['user_id'], unique=False)

    op.create_table('crm_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommended_next_action', sa.String(), nullable=True),
    sa.Column('buying_intent', sa.Float(), nullable=True),
    sa.Column('urgency', sa.Float(), nullable=True),
    sa.Column('hiring_intent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_leads_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_user_id'), ['user_id'], unique=False)

    op.create_table('crm_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_notes_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_notes_user_id'), ['user_id'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('stage_moved_at', sa.DateTime(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True),
    sa.Column('actual_close_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('close_reason', sa.String(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_name'), ['name'], unique=False)

    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('gmail_message_id', sa.String(), nullable=True),
    sa.Column('gmail_thread_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('draft_reply', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_gmail_message_id'), ['gmail_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_emails_gmail_thread_id'), ['gmail_thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_id'), ['id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('temperature', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('timeline', sa.String(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=True),
    sa.Column('intent_detected', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_id'), ['id'], unique=False)

    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_recommendations_id'), ['id'], unique=False)

    op.create_table('campaign_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('send_id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('referer', sa.String(length=512), nullable=True),
    sa.Column('link_url', sa.String(length=512), nullable=True),
    sa.Column('tracked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['send_id'], ['campaign_sends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_tracks_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_tracks_send_id'), ['send_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_tracks_tracked_at'), ['tracked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_tracks_tracking_id'), ['tracking_id'], unique=False)

    op.create_table('crm_deal_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_impact', sa.Float(), nullable=True),
    sa.Column('probability_impact', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_deal_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_deal_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deal_activities_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deal_activities_id'), ['id'], unique=False)

    op.create_table('win_loss_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('outcome_date', sa.DateTime(), nullable=True),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('key_factors', sa.JSON(), nullable=True),
    sa.Column('competitor', sa.String(), nullable=True),
    sa.Column('competitor_solution', sa.String(), nullable=True),
    sa.Column('final_value', sa.Float(), nullable=True),
    sa.Column('sales_cycle_days', sa.Integer(), nullable=True),
    sa.Column('contact_count', sa.Integer(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('lessons_learned', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('win_loss_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_win_loss_analysis_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('win_loss_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_win_loss_analysis_id'))

    op.drop_table('win_loss_analysis')
    with op.batch_alter_table('crm_deal_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_deal_activities_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deal_activities_deal_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deal_activities_created_at'))

    op.drop_table('crm_deal_activities')
    with op.batch_alter_table('campaign_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_tracks_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_tracks_tracked_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_tracks_send_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_tracks_campaign_id'))

    op.drop_table('campaign_tracks')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_id'))

    op.drop_table('ai_recommendations')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_id'))

    op.drop_table('leads')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_id'))
        batch_op.drop_index(batch_op.f('ix_emails_gmail_thread_id'))
        batch_op.drop_index(batch_op.f('ix_emails_gmail_message_id'))

    op.drop_table('emails')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_name'))
        batch_op.drop_index(batch_op.f('ix_deals_id'))

    op.drop_table('deals')
    with op.batch_alter_table('crm_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_notes_id'))
        batch_op.drop_index(batch_op.f('ix_crm_notes_created_at'))
        batch_op.drop_index(batch_op.f('ix_crm_notes_contact_id'))

    op.drop_table('crm_notes')
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_leads_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_score'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_label'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_id'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_created_at'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_contact_id'))

    op.drop_table('crm_leads')
    with op.batch_alter_table('crm_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_interactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_crm_interactions_id'))
        batch_op.drop_index(batch_op.f('ix_crm_interactions_gmail_message_id'))
        batch_op.drop_index(batch_op.f('ix_crm_interactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_crm_interactions_contact_id'))

    op.drop_table('crm_interactions')
    with op.batch_alter_table('crm_deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_deals_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_status'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_stage'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_expected_close_at'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_created_at'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_contact_id'))

    op.drop_table('crm_deals')
    with op.batch_alter_table('crm_customer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_customer_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_customer_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_crm_customer_profiles_created_at'))

    op.drop_table('crm_customer_profiles')
    with op.batch_alter_table('crm_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_type'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_status'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_id'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_due_at'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_contact_id'))

    op.drop_table('crm_activities')
    with op.batch_alter_table('contact_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_relationships_id'))

    op.drop_table('contact_relationships')
    with op.batch_alter_table('campaign_sends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_sends_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_sends_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_sends_recipient_email'))
        batch_op.drop_index(batch_op.f('ix_campaign_sends_created_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_sends_contact_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_sends_campaign_id'))

    op.drop_table('campaign_sends')
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_email'))
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_created_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_campaign_id'))

    op.drop_table('campaign_recipients')
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_insights_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_insight_type'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_id'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_created_at'))

    op.drop_table('ai_insights')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_id'))

    op.drop_table('activities')
    with op.batch_alter_table('territory_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territory_metrics_id'))

    op.drop_table('territory_metrics')
    with op.batch_alter_table('task_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_records_task_type'))
        batch_op.drop_index(batch_op.f('ix_task_records_status'))
        batch_op.drop_index(batch_op.f('ix_task_records_queue'))
        batch_op.drop_index(batch_op.f('ix_task_records_id'))
        batch_op.drop_index(batch_op.f('ix_task_records_created_at'))

    op.drop_table('task_records')
    with op.batch_alter_table('sales_cycle_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_cycle_metrics_id'))

    op.drop_table('sales_cycle_metrics')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('gmail_sync_cursors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmail_sync_cursors_user_id'))
        batch_op.drop_index(batch_op.f('ix_gmail_sync_cursors_id'))
        batch_op.drop_index(batch_op.f('ix_gmail_sync_cursors_created_at'))

    op.drop_table('gmail_sync_cursors')
    with op.batch_alter_table('forecast_accuracy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_accuracy_id'))

    op.drop_table('forecast_accuracy')
    with op.batch_alter_table('email_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_metadata_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_metadata_thread_id'))
        batch_op.drop_index(batch_op.f('ix_email_metadata_sender_email'))
        batch_op.drop_index(batch_op.f('ix_email_metadata_sender'))
        batch_op.drop_index(batch_op.f('ix_email_metadata_internal_date'))
        batch_op.drop_index(batch_op.f('ix_email_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_email_metadata_gmail_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_metadata_created_at'))
        batch_op.drop_index(batch_op.f('ix_email_metadata_body_fetched'))
        batch_op.drop_index(batch_op.f('ix_email_metadata_ai_status'))
        batch_op.drop_index('ix_email_meta_user_status')
        batch_op.drop_index('ix_email_meta_user_sender')
        batch_op.drop_index('ix_email_meta_user_date')

    op.drop_table('email_metadata')
    with op.batch_alter_table('email_classification_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_email_rule_user_domain')
        batch_op.drop_index('ix_email_rule_user_category')
        batch_op.drop_index(batch_op.f('ix_email_classification_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_classification_rules_sender_email'))
        batch_op.drop_index(batch_op.f('ix_email_classification_rules_sender_domain'))
        batch_op.drop_index(batch_op.f('ix_email_classification_rules_id'))
        batch_op.drop_index(batch_op.f('ix_email_classification_rules_created_at'))
        batch_op.drop_index(batch_op.f('ix_email_classification_rules_category'))

    op.drop_table('email_classification_rules')
    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_contacts_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_last_interaction_at'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_created_at'))

    op.drop_table('crm_contacts')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))

    op.drop_table('contacts')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_user_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_sent_count'))
        batch_op.drop_index(batch_op.f('ix_campaigns_name'))
        batch_op.drop_index(batch_op.f('ix_campaigns_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_created_at'))

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key'))
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_id'))

    op.drop_table('workspaces')
    # ### end Alembic commands ###
