import { PERMISSIONS } from "./permissions";
import { ROLES } from "./roles";

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.WORKSPACE_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.VIEWER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.INBOX_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.WORKFLOWS_VIEW,
  ],

  [ROLES.SALES]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.INBOX_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_EDIT,
    PERMISSIONS.PIPELINES_VIEW,
    PERMISSIONS.PIPELINES_EDIT,
    PERMISSIONS.DEALS_VIEW,
    PERMISSIONS.DEALS_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AI_REPLY,
    PERMISSIONS.AI_CLASSIFY,
    PERMISSIONS.AI_SCORE,
    PERMISSIONS.AI_ANALYTICS,
    PERMISSIONS.WORKFLOWS_VIEW,
    PERMISSIONS.WORKFLOWS_MANAGE,
    PERMISSIONS.APPROVALS_VIEW,
  ],

  [ROLES.RECRUITER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.HIRING_VIEW,
    PERMISSIONS.CANDIDATES_VIEW,
    PERMISSIONS.WORKFLOWS_VIEW,
  ],

  [ROLES.MARKETING]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CAMPAIGNS_VIEW,
    PERMISSIONS.CAMPAIGNS_CREATE,
    PERMISSIONS.CAMPAIGNS_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AI_ANALYTICS,
    PERMISSIONS.WORKFLOWS_VIEW,
    PERMISSIONS.WORKFLOWS_MANAGE,
  ],

  [ROLES.SUPPORT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.INBOX_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.AI_REPLY,
    PERMISSIONS.WORKFLOWS_VIEW,
    PERMISSIONS.APPROVALS_VIEW,
  ],

  [ROLES.SECURITY_ANALYST]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.INBOX_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.SETTINGS_SECURITY,
    PERMISSIONS.SETTINGS_AUDIT_LOGS,
    PERMISSIONS.WORKFLOWS_VIEW,
    PERMISSIONS.APPROVALS_VIEW,
  ],
};
